language: R
cache: packages
pandoc_version: 1.19
script: /bin/bash gh-publisher-scripts/gh-publisher.sh
before_install:
- echo installing latex packages
- yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get install -y
     inkscape
     texlive-fonts-recommended
     texlive-latex-extra
     texlive-latex-recommended
     texlive-xetex
- pdftex --version
- tlmgr install xpatch kpfonts
- wget http://mirror.ctan.org/install/fonts/carlito.tds.zip
- unzip carlito.tds.zip -d /home/travis/texlive/texmf-dist
- texhash
notifications:
  email: false
after_success:
- chmod +x tools/deploy.sh
- tools/deploy.sh
