* Readme.org
** this is not sourced on github, that file is README.md
** TODO make the .md from this .org using pandoc on travis (priority: very low)
** this directory is stored on github.com/benyomin/workingDec
*** it is public, be careful what you type or put here.
** Webpage for thesis proposal.
         
*** changelog
         v. 1.3.3 - displayed pdf is now publishedVersion.pdf compiled from publishedVersion.Rmd
                  - HEAD is in decPropv#.Rmd
         v. 1.3.7 - actually compiled once, adding local copy of savesym.sty, apt-get installs a very old version of tex-live, I'm using a newer from a .deb, but there is a problem with installing packages on the fly that are declared with \require{package} in a .tex file
         v. 1.3.9 - works, except for text below H3, which overflows the margins, possible I commented out the H3 definition. Will make section H2 without a subheading for workaround.
         v. 1.4   - script to download Carlito font and install to tex-live distribution
         v. 1.4.1 - try to send log files back to github
         v. 1.4.2 - builds locally after removing ukdate dependency (this fixed no /begin document)
         v. 1.4.3 - file xpatch.sty
* View latest version.
Leave comments as Issues.
* Workflow inspired by [Marshall](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy), who claims benefits from early access to peer-review of his pre-publication project.

** Latex example [commit](https://github.com/benyomin/benyomin.github.io/commit/2ad2af57e7a6342d267dc113f9bf3486d232a8bd)

### is a working [build](https://travis-ci.org/benyomin/benyomin.github.io/builds/159376552)

## Sweave example
[commit](https://github.com/benyomin/benyomin.github.io/commit/76e3a8dcbb4b817afdfc9729780a40c6352e297a)
### is a working [build](https://travis-ci.org/benyomin/benyomin.github.io/builds/159660865)
