* Readme.org
** this is not sourced on github, that file is README.md
** TODO make the .md from this .org using pandoc on travis (priority: very low)
** this directory is stored on github.com/benyomin/workingDec
*** it is public, be careful what you type or put here.
** Webpage for thesis proposal.
 
* Data Sources:        
** Consumption: 
   Household Expenditure Survey, 2002-2015
** GDP:
   The World Bank - 
file is included with the project as:
/rawData/Data_Extract_From_World_Development_Indicators/0e59101e-51e1-4d8b-a2c1-94d8c676e667_Data.csv
source:
http://databank.worldbank.org/data/reports.aspx?ReportId=46991
click "Download Options" "csv"

*** changelog
         v. 1.3.3 - displayed pdf is now publishedVersion.pdf compiled from publishedVersion.Rmd
                  - HEAD is in decPropv#.Rmd
         v. 1.3.7 - actually compiled once, adding local copy of savesym.sty, apt-get installs a very old version of tex-live, I'm using a newer from a .deb, but there is a problem with installing packages on the fly that are declared with \require{package} in a .tex file
         v. 1.3.9 - works, except for text below H3, which overflows the margins, possible I commented out the H3 definition. Will make section H2 without a subheading for workaround.
         v. 1.4   - script to download Carlito font and install to tex-live distribution
         v. 1.4.1 - try to send log files back to github
         v. 1.4.2 - builds locally after removing ukdate dependency (this fixed no /begin document)
         v. 1.4.3 - file xpatch.sty
         v. 1.4.4 - builds on travis! after tlmgr install kpfonts
         v. 1.4.5 - gh-publisher fixes
         v. 1.4.6 - trash gh-publisher branch
         v. 1.4.7 - deploy unit tests
         v. 1.4.8 - rebase, working Makefile
* View latest version.
Leave comments as Issues.
* This piece of reproducible research  
compiles a Rmarkdown document consisting of code and narrative into a pdf.
* Webpage which displays latest compiled proof of the project uses github publisher. 
[Dr. Phil Marshall](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy)
[Ewan Mellor](https://github.com/ewanmellor/gh-publisher)
