* Readme.org
** don't touch me!
I'm actually working at the moment.  It seems that the automatic Travis compilation
isn't doing anything at the moment. Check which commit adds this line to find out 
which change actually changes the displayed pdf.
** Thesis template:
*** Reed is in development, may have good M$ Word export soon
https://github.com/ismayc/thesisdown
**** Reed uses multiple chapters.
*** changes from Monash:
I modified the monashwp.sty, it's now benyomin.wp.sty
**** uses my uni logo 
**** uses US not UK dates
seems to be 
*** Monash
http://robjhyndman.com/hyndsight/rmarkdown-template/
**** single preamble is separate, then all chapters in one File?
rather than
*** Reed
http://blogs.reed.edu/ed-tech/2015/11/r-markdown-senior-thesis-template/
**** distributed as thesisdown package
```{r}
devtools::install_github("ismayc/thesisdown")
```
****
** this is not sourced on github, that file is README.md
** TODO make the .md from this .org using pandoc on travis (priority: very low)
** this directory is stored on github.com/benyomin/workingDec
*** it is public, be careful what you type or put here.
** Webpage for thesis proposal.
 
* Data Sources:        
** Consumption: 
   Household Expenditure Survey, 2002-2015
** GDP:
   The World Bank - 
file is included with the project as:
/rawData/Data_Extract_From_World_Development_Indicators/0e59101e-51e1-4d8b-a2c1-94d8c676e667_Data.csv
source:
http://databank.worldbank.org/data/reports.aspx?ReportId=46991
click "Download Options" "csv"

* changelog
** 1.5.3 - use marchDraft ; fix Hmisc dependency (survival > 0.4) 
-----------------------------
** 1.3.7 - actually compiled once, adding local copy of savesym.sty, apt-get installs a very old version of tex-live, I'm using a newer from a .deb, but there is a problem with installing packages on the fly that are declared with \require{package} in a .tex file
** 1.3.9 - works, except for text below H3, which overflows the margins, possible I commented out the H3 definition. Will make section H2 without a subheading for workaround.
** 1.4   - script to download Carlito font and install to tex-live distribution
** 1.4.1 - try to send log files back to github
** 1.4.2 - builds locally after removing ukdate dependency (this fixed no /begin document)
** 1.4.3 - file xpatch.sty
** 1.4.4 - builds on travis! after tlmgr install kpfonts
** 1.4.5 - gh-publisher fixes
** 1.4.6 - trash gh-publisher branch
** 1.4.7 - deploy unit tests
** 1.4.8 - rebase, working Makefile
** 1.4.9 - webpage working
** 1.5   - kislevDraft.Rmd  
*** remove reproducibility section
*** remove references that aren't cited
*** remove JEL classifications
** 1.5.1 - kanban
** 1.5.2 - use febDraft
* View latest version.
Leave comments as Issues.
* This piece of reproducible research  
compiles a Rmarkdown document consisting of code and narrative into a pdf.
* Webpage which displays latest compiled proof of the project uses github publisher. 
[Dr. Phil Marshall](https://github.com/drphilmarshall/Ideas-for-Citizen-Science-in-Astronomy)
[Ewan Mellor](https://github.com/ewanmellor/gh-publisher)
