## version 0.9
#  transitioning from proposal to thesisdown package
#install.packages("devtools")
source("./includes/install_if_needed.R",echo=FALSE)
install_if_needed("devtools")
library(devtools)
install_github("benyomin/censusFunctions")
library(censusFunctions)
##loadWealthEffectPackages()
install_if_needed("knitr")
install_if_needed("RCurl")
library(RCurl)
install_if_needed("rJava")
library(rJava)
install_if_needed("rmarkdown")
install_if_needed("xlsx")
library(xlsx)
library(rmarkdown)
install_if_needed("bookdown")
#install_if_needed("thesisdown")
devtools::install_github("ismayc/thesisdown")
library(bookdown)
library(knitr)
#source("./includes/updatePackage.R",echo=FALSE)
#file.copy(from='kislevDraft.Rmd',to='currentWorkingDraft.Rmd',overwrite=TRUE)
file.copy(from='febDraft.Rmd',to='currentWorkingDraft.Rmd',overwrite=TRUE)
rmarkdown::render('currentWorkingDraft.Rmd')
file.rename(from='currentWorkingDraft.pdf', to='./proofs/workingDraft.pdf')
